name: eeg_audio_anotator
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.14
  - astroid=3.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - contourpy=1.2.1
  - cycler=0.12.1
  - dill=0.3.8
  - fonttools=4.52.1
  - idna=3.7
  - isort=5.13.2
  - jinja2=3.1.4
  - kiwisolver=1.4.5
  - lazy_loader=0.4
  - markupsafe=2.1.5
  - matplotlib=3.9.0
  - mccabe=0.7.0
  - mne=1.7.0
  - numpy=1.26.4
  - pandas=2.2.2
  - pillow=10.3.0
  - pooch=1.8.1
  - pycparser=2.22
  - pylint=3.2.2
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqtgraph=0.13.7
  - python-dotenv=1.0.1
  - pytz=2024.1
  - pywin32=306
  - pyxdf=1.16.6
  - qt=5.15.2
  - requests=2.32.2
  - scipy=1.13.1
  - soundfile=0.12.1
  - tomli=2.0.1
  - tomlkit=0.12.5
  - tqdm=4.66.4
  - tzdata=2024.1
  - urllib3=2.2.1
  - pip
  - pip:
    - PyAudio==0.2.14
    - pyqt5-plugins==5.15.9.2.3
    - pyqt5-sip==12.13.0
    - pyqt5-tools==5.15.9.3.3
    - qt5-applications==5.15.2.2.3
    - qt5-tools==5.15.2.1.3
    - -e .  